' Gambas module file

' Author Westwood JustLostintime
'Released Under:
'  GNU GENERAL Public LICENSE
'  Version 3, 29 June 2007
'  See project license file.

Public XaInstalled As Boolean = False

Public Sub _init()

  If Not Exist("/tmp/gambasAsm/dasm") Then
    Print ("Installing assembler to /tmp/gambasAsm")
    Try Shell.MkDir("/tmp/gambasAsm")
    Copy "dasm" To "/tmp/gambasAsm/dasm"
    Chmod "/tmp/gambasAsm/dasm" To "rwxr-xr-x"
  Endif

End

Public Sub _call(source As String, Dest As String, listing As String, symbols As String, SearchPaths As String[]) As String

  Dim Result As String
  Dim cmd As String[]

  cmd = ["/tmp/gambasAsm/dasm", Source, "-o" & Dest, "-l" & listing, "-s" & symbols]

  For Each s As String In SearchPaths
    cmd.Add("-I" & s)
  Next

  Exec cmd To result

  Result = Replace(result, "\n", "\n\r")
  If Exist(listing) Then Result &= "\n\r" & ("Listing available") & "  " & Listing & "\n\r" & ("Binary Generated") & " " & Dest & "\n\r"

  Return result

End
