' Gambas class file

Inherits Task

'Fast Unsafe

Extern getchar() As Integer In "libc:6"

KeyboardInput As Integer
TermCtlOld As TerminalSettings
TermCtlNew As TerminalSettings

Public Sub main()

  wait 1.0
  File.in.term.echo = False

  TermCtlOld = File.In.Term.GetAttr()
  TermCtlNew = TermCtlOld.Copy()

  TermCtlNew.ICANON = False
  TermCtlNew.MakeRaw()

  File.In.Term.SetAttr(0, TermCtlNew)

  While True

    Wait 0.01
    KeyboardInput = getchar()
    If KeyboardInput <> -1 Then
     flush #file.err
      Write #File.out, Chr(KeyboardInput), 1
      Flush #File.out
    Endif

  Wend

Catch
  Error "KeyboardRdr Error: "; Error.text, Error.Where

End